version: '3.8'


services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile
    image: docker-assessment-web:latest
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - REDIS_URL=redis://redis:6379/0
      - DOCKER_HOST=unix:///var/run/docker.sock
    depends_on:
      - redis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: docker-assessment-nginx:latest
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - app-network


  redis:
    image: redis:7-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network


networks:
  app-network:
    driver: bridge